blank_issues_enabled: false
contact_links:
  - name: op Discord
    url: https://discord.gg/op-pas-op
    about: You can also visit the Official Discord, if you want to follow the development, the RoadMap and the many announcements to come !
